{{- if .Values.rbac.create }}
apiVersion: {{ include "tarantool-operator.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ include "tarantool-operator.fullname" . }}
  labels: {{- include "tarantool-operator.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{- tpl (.Values.annotations | toYaml) $ | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tarantool-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tarantool-operator.service-account.name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
