{{- $password := (include "cartridge.auth.password.b64" . | trim) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cartridge.resource.fullname" (dict "context" . "suffix" "auth") }}
  labels: {{- include "cartridge.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{- tpl (.Values.annotations | toYaml) $ | nindent 4 }}
  {{- end }}
data:
  TARANTOOL_PASSWORD: {{ $password }}
  TARANTOOL_CLUSTER_COOKIE: {{ $password }}
